### ISSUE TITLE
Licensing terms are unclear

### ISSUE THREAD

**Issue by oxr463** [mcroteau/Apollo#3]
Does the [`MIT license`](https://github.com/mcroteau/Oa/blob/master/java-web/License.md) in `java-web/` apply to more than just that directory? What is the license for the other files?

**Comment by mcroteau** [comment]
You are free to do as you wish with the project except commercial use! No selling, especially the user experience.

**Comment by oxr463** [comment]
Per the [Open Source Definition](https://opensource.org/osd),

> The license shall not restrict any party from selling or giving away the software as a component of an aggregate software distribution containing programs from several different sources. The license shall not require a royalty or other fee for such sale.

Also, the MIT license also permits commercial use, or really any use since it is a very permissive license.

**Comment by mcroteau** [comment]
What do you recommend? I did some searching and found out that I can modify the License, which is what I did.

**Comment by oxr463** [comment]
I would recommend using a copyleft license such as the [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html), since any changes that are contributed must be reciprocated. And also, keep in mind that as the author, you can multi-license your program under more than one license. So for example, I can contribute changes and use the program commercially or otherwise; but if I wanted to keep my changes for myself, then I would simply purchase a commercial license from you. This is how [qt](https://www.qt.io) is handled, (See also: https://opensource.stackexchange.com/a/8894/8868).

**Comment by mcroteau** [comment]
Go ahead and change the licensing if you wish! Thank you.

**Comment by mcroteau** [comment]
The license is an adjusted MIT license.
